// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	HMRequest
	HMResponse
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HMRequest struct {
	Action           *string `protobuf:"bytes,1,req,name=action" json:"action,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=method" json:"method,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	Callback         *string `protobuf:"bytes,4,opt,name=callback" json:"callback,omitempty"`
	ChannelId        *int32  `protobuf:"varint,5,opt,name=channelId" json:"channelId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HMRequest) Reset()                    { *m = HMRequest{} }
func (m *HMRequest) String() string            { return proto.CompactTextString(m) }
func (*HMRequest) ProtoMessage()               {}
func (*HMRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HMRequest) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *HMRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *HMRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HMRequest) GetCallback() string {
	if m != nil && m.Callback != nil {
		return *m.Callback
	}
	return ""
}

func (m *HMRequest) GetChannelId() int32 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

type HMResponse struct {
	Callback         *string `protobuf:"bytes,1,req,name=callback" json:"callback,omitempty"`
	Code             *int32  `protobuf:"zigzag32,2,req,name=code" json:"code,omitempty"`
	Data             []byte  `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	IsCompress       *bool   `protobuf:"varint,4,req,name=isCompress" json:"isCompress,omitempty"`
	Msg              *string `protobuf:"bytes,5,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HMResponse) Reset()                    { *m = HMResponse{} }
func (m *HMResponse) String() string            { return proto.CompactTextString(m) }
func (*HMResponse) ProtoMessage()               {}
func (*HMResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HMResponse) GetCallback() string {
	if m != nil && m.Callback != nil {
		return *m.Callback
	}
	return ""
}

func (m *HMResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *HMResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HMResponse) GetIsCompress() bool {
	if m != nil && m.IsCompress != nil {
		return *m.IsCompress
	}
	return false
}

func (m *HMResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HMRequest)(nil), "HMRequest")
	proto.RegisterType((*HMResponse)(nil), "HMResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8e, 0xb1, 0x4e, 0xc5, 0x20,
	0x18, 0x85, 0x03, 0xa5, 0xa6, 0xfc, 0x71, 0x50, 0x06, 0x43, 0x8c, 0x31, 0xa4, 0x13, 0x93, 0x0f,
	0xa1, 0x8b, 0x0e, 0x2e, 0xff, 0xe8, 0x86, 0x40, 0x6c, 0x63, 0x0b, 0xb5, 0xe0, 0x0b, 0xb8, 0xf9,
	0xd6, 0x06, 0x6a, 0x6e, 0xef, 0x4d, 0xee, 0x74, 0xce, 0xf9, 0x86, 0x93, 0x0f, 0xc0, 0x99, 0x6c,
	0x1e, 0x96, 0x35, 0xe6, 0xd8, 0xff, 0x12, 0xe0, 0xcf, 0xaf, 0xe8, 0xbf, 0xbe, 0x7d, 0xca, 0xe2,
	0x06, 0x2e, 0x8c, 0xcd, 0x63, 0x0c, 0x92, 0x28, 0xaa, 0x39, 0xfe, 0xaf, 0xc2, 0x67, 0x9f, 0x87,
	0xe8, 0x24, 0xdd, 0xf8, 0xb6, 0x84, 0x00, 0x56, 0xbe, 0x64, 0xa3, 0xa8, 0xbe, 0xc4, 0xda, 0xc5,
	0x2d, 0x74, 0xd6, 0x4c, 0xd3, 0xbb, 0xb1, 0x9f, 0x92, 0x29, 0xa2, 0x39, 0x1e, 0xb6, 0xb8, 0x03,
	0x6e, 0x07, 0x13, 0x82, 0x9f, 0x5e, 0x9c, 0x6c, 0x15, 0xd1, 0x2d, 0xee, 0xa0, 0xff, 0x21, 0x00,
	0xc5, 0x25, 0x2d, 0x31, 0x24, 0x7f, 0x72, 0xb4, 0xe9, 0xec, 0x47, 0x02, 0x98, 0x8d, 0xce, 0x57,
	0x9d, 0x6b, 0xac, 0xfd, 0xac, 0xcc, 0x3d, 0xc0, 0x98, 0x9e, 0xe2, 0xbc, 0xac, 0x3e, 0x25, 0xc9,
	0x14, 0xd5, 0x1d, 0x1e, 0x11, 0x71, 0x05, 0xcd, 0x9c, 0x3e, 0xaa, 0x0a, 0xc7, 0x52, 0x1f, 0xdb,
	0xb7, 0x12, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x7e, 0x9e, 0xad, 0x24, 0x01, 0x00, 0x00,
}
